### ISSUE TITLE
Properly handle multiple results for a gitlab username

### ISSUE THREAD

**Issue by LinuxMercedes** [grade-it/assigner#15]
I found one case where we actually will regularly get multiple results, thanks to @brhoades. IT students get separate trusted accounts named 't-SSO' (so mine would be t-nmjxv3). Naturally, a search for the plain SSO turns up both their normal and trusted accounts, and students whose first initial comes alphabetically after 't' (or who have displeased the RNG gods; it's unclear how the list of results is sorted) will accidentally get their homework assigned to their IT trusted account instead of their normal one. 

FUN.

**Comment by brhoades** [comment]
Just helping you find edge cases. What if "ff" wanted a repository? You'd have so many matches.

**Comment by LinuxMercedes** [comment]
PR #16 searches through the results list for an exact match and falls back to the first result if it doesn't find one. Should fix 'ff' too!
