### ISSUE TITLE
Student gitlab usernames are based on their email alias

### ISSUE THREAD

**Issue by LinuxMercedes** [grade-it/assigner#18]
...not their SSO. 

What the fuck. 

Also, aliases usually have `.` in them, so that means we need URL encoding, I think.

**Comment by michaelwisely** [comment]
Are you telling me that I could have had my alias as my username?

I am so grumpy right now. :grimacing:

**Comment by LinuxMercedes** [comment]
Yeah I have no idea how he managed that! I thought I also had my alias when I signed in to gitlab.

**Comment by LinuxMercedes** [comment]
Okay, this is a legit GitLab bug. I'll still write the code to handle it and manually set the `userid` for my one edge case student.
